name: Build iStoreOS for QHORA-301W with 2.5G USB Support

on:
  workflow_dispatch:
  push:
    branches: [ main ]

env:
  TARGET: qualcommax
  SUBTARGET: ipq807x
  PROFILE: qhora-301w

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 240

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up environment
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential clang flex bison g++ gawk gcc-multilib g++-multilib \
          gettext git libncurses5-dev libssl-dev python3-distutils rsync unzip zlib1g-dev \
          file wget curl cmake libelf-dev

    - name: Clone OpenWrt source
      run: |
        git clone --depth=1 -b openwrt-23.05 https://github.com/openwrt/openwrt.git
        cd openwrt

    - name: Prepare feeds
      run: |
        echo "src-git packages https://git.openwrt.org/feed/packages.git^b1c8f8b1e8b4f5c7a1d1f1a1b1c1d1e1f1a1b1c" > feeds.conf
        echo "src-git luci https://git.openwrt.org/project/luci.git^a1b2c3d4e5f6a1b2c3d4e5f6a1b2c3d4e5f6a1b2" >> feeds.conf
        echo "src-git routing https://git.openwrt.org/feed/routing.git^1a2b3c4d5e6f1a2b3c4d5e6f1a2b3c4d5e6f1a2b" >> feeds.conf
        echo "src-git istore https://github.com/linkease/istore.git^main" >> feeds.conf
        echo "src-git istore_packages https://github.com/linkease/istore-packages.git^main" >> feeds.conf
        ./scripts/feeds update -a
        ./scripts/feeds install -a

    - name: Add USB 2.5G Ethernet support
      run: |
        cd openwrt
        # 添加R8152驱动包
        git clone https://github.com/bb-qq/r8152-openwrt.git package/kernel/r8152
        
        # 更新配置以包含USB和网络驱动
        cat >> .config <<EOF
        # USB 支持
        CONFIG_PACKAGE_kmod-usb-core=y
        CONFIG_PACKAGE_kmod-usb2=y
        CONFIG_PACKAGE_kmod-usb3=y
        CONFIG_PACKAGE_kmod-usb-storage=y
        CONFIG_PACKAGE_kmod-usb-ohci=y
        CONFIG_PACKAGE_kmod-usb-uhci=y
        CONFIG_PACKAGE_kmod-usb-net=y
        CONFIG_PACKAGE_kmod-usb-net-asix=y
        CONFIG_PACKAGE_kmod-usb-net-asix-ax88179=y
        CONFIG_PACKAGE_kmod-usb-net-rtl8152=y
        CONFIG_PACKAGE_kmod-usb-net-r8152=y
        CONFIG_PACKAGE_kmod-usb-net-cdc-ether=y
        CONFIG_PACKAGE_kmod-usb-net-cdc-mbim=y
        CONFIG_PACKAGE_kmod-usb-net-cdc-ncm=y
        CONFIG_PACKAGE_kmod-usb-net-huawei-cdc-ncm=y
        CONFIG_PACKAGE_kmod-usb-net-kalmia=y
        CONFIG_PACKAGE_kmod-usb-net-sierrawireless=y
        CONFIG_PACKAGE_kmod-usb-net-qmi-wwan=y
        CONFIG_PACKAGE_kmod-usb-net-ipheth=y
        CONFIG_PACKAGE_kmod-usb-net-aqc111=y
        
        # 文件系统支持
        CONFIG_PACKAGE_kmod-fs-ext4=y
        CONFIG_PACKAGE_kmod-fs-ntfs=y
        CONFIG_PACKAGE_kmod-fs-vfat=y
        CONFIG_PACKAGE_kmod-fs-exfat=y
        
        # R8152 驱动
        CONFIG_PACKAGE_kmod-r8152=y
        CONFIG_PACKAGE_r8152-firmware=y
        EOF

    - name: Configure for QHORA-301W
      run: |
        cd openwrt
        cat >> .config <<EOF
        CONFIG_TARGET_qualcommax=y
        CONFIG_TARGET_qualcommax_ipq807x=y
        CONFIG_TARGET_qualcommax_ipq807x_DEVICE_qhora-301w=y
        CONFIG_PACKAGE_luci-app-istorex=y
        CONFIG_PACKAGE_luci-i18n-istorex-zh-cn=y
        CONFIG_PACKAGE_istore-core=y
        CONFIG_PACKAGE_istore-ui=y
        EOF
        make defconfig

    - name: Download dependencies
      run: |
        cd openwrt
        make download -j$(nproc)
        find dl -size -1024c -exec rm -f {} \;

    - name: Build firmware
      run: |
        cd openwrt
        make -j$(($(nproc) + 1)) V=s

    - name: Upload artifacts
      uses: actions/upload-artifact@v3
      if: success()
      with:
        name: iStoreOS-QHORA-301W-2.5G-USB
        path: openwrt/bin/targets/qualcommax/ipq807x/*.bin
        retention-days: 7
